### ISSUE TITLE
For android 👀

### ISSUE THREAD

**Issue by rac14** [IJustNeedOffsets/MCPE-Modding#1]
...

**Comment by IJustNeedOffsets** [comment]
That is not even a issue.. However i will look into adding capes to the minecraft apk and update this as soon as possible.

**Comment by IJustNeedOffsets** [comment]
Added support for iOS and Android with the new update.
You can get the latest version here: https://github.com/IJustNeedOffsets/MCPE-Modding/releases/tag/1.1
